---

- name: "UNIT TESTING THE NETWORK CONFIG BUILD PROCESS"
  hosts: "{{ test_hosts | default('all') }}"
  gather_facts: no
  connection: "local"

  vars:
    output_dir: "tests/outputs"
    test_dir: "tests"
    mock_path: "{{ test_dir }}/config_gen/mocks"
    template_dir: "{% set env_var = lookup('env', 'TEMPLATE_DIR') %}{% if env_var %}{{ env_var }}{% else %}templates{% endif %}"

  tasks:

    - name: "MAIN: GATHER ALL MOCK DIRECTORIES"
      set_fact:
        mock_directories: "{{ lookup('pipe', 'ls ' ~ mock_path).splitlines() }}"
      register: "mock_directories"
      delegate_to: "localhost"

    - name: "MAIN: REMOVE PREVIOUS OUTPUT DIRECTORIES"
      file:
        path: "{{ output_dir }}"
        state: "absent"
      delegate_to: "localhost"
      run_once: true
      
    - name: "MAIN: REMOVE LAST JOB SUMMARY FILE"
      file:
        path: "job-summary.txt"
        state: "absent"
      delegate_to: "localhost"
      run_once: true

    - name: "MAIN: CREATE REQUIRED OUTPUT DIRECTORY STRUCTURE 01"
      file:
        path: "{{ output_dir }}/reports"
        state: "directory"
      delegate_to: "localhost"

    - name: "MAIN: CREATE REQUIRED OUTPUT DIRECTORY STRUCTURE 02"
      file:
        path: "/tmp/ntc"
        state: "directory"
      delegate_to: "localhost"

    - name: "MAIN: EXECUTE TESTS"
      include_tasks: "tasks_config_tester.yml"
      loop: "{{ mock_directories }}"
      loop_control:
        loop_var: "mock_dir"
      delegate_to: "localhost"

    - name: "MAIN: GENERATE MASTER LOG"
      assemble:
        src: "./{{ output_dir }}/reports/"
        dest: "job-summary.txt"
        delimiter: "\n"
      delegate_to: "localhost"
      run_once: true

    - name: "MAIN: ADD HEADER TO MASTER LOG"
      lineinfile:
        path: "job-summary.txt"
        insertbefore: BOF
        line: |
          Configuration Build Testing Job Summary
             -> Ansible Version: {{ ansible_version['full']}}
             -> Python Version: {{ ansible_playbook_python | basename | default('N/A') }}
          -------------------------------------------------------------
      delegate_to: "localhost"
      run_once: true

    - name: "MAIN: ADD SUMMARY TO MASTER LOG"
      lineinfile:
        path: "job-summary.txt"
        insertafter: "EOF"
        line: |

          Summary: {{ mock_directories | length }} features tested for {{ ansible_play_hosts | length }} hosts
      delegate_to: "localhost"
      run_once: true

    - name: "MAIN: SHOW STATUS SUMMARY"
      debug:
        msg: >
          View job-summary.txt in the project path to view 
          the Job Summary.
      delegate_to: "localhost"
      run_once: true

    - name: "COPY REPORT TO TMP FOR VIEWING OF VENV TESTS"
      copy:
        src: "./job-summary.txt"
        dest: "/tmp/ntc/{{ lookup('pipe','date +%Y-%m-%d-%H-%M-%S') }}-ansible{{ ansible_version['full']}}-{{ ansible_playbook_python | basename | default('NA') }}-job-summary.txt"
      delegate_to: "localhost"
      run_once: true

