---

  # mock_dir is name of the config feature being tested
  # the initating loop can be found in 
  # the playbook iterating over all data files
  # look for MAIN: EXECUTE ALL TESTS task
  - name: "{{ mock_dir | upper }}-> SET PATH"
    set_fact:
      test_path: "{{ output_dir }}/{{ mock_dir }}/{{ inventory_hostname }}"
    delegate_to: "localhost"

  - name: "{{ mock_dir | upper }}-> CREATE DIRECTORY STRUCTURE"
    file:
      path: "{{ test_path }}/{{ mock_dir }}"
      state: "directory"
    delegate_to: "localhost"

  - name: "{{ mock_dir | upper }}-> GENERATE CONFIG"
    template:
      src: "{{ lookup('first_found', file_paths) }}"
      dest: "./{{ test_path }}/{{ mock_dir }}/{{ inventory_hostname }}.cfg"
    vars:
      file_paths:
        files: "{{ mock_dir }}.j2"
        paths:
          - "{{ test_dir }}/config_gen/templates"
          - "{{ template_dir }}/{{ vendor }}/{{ ansible_network_os }}/{{ platform | default('') }}/{{ family | default('') }}/{{ model | default('') }}"
          - "{{ template_dir }}/{{ vendor }}/{{ ansible_network_os }}/{{ platform | default('') }}/{{ family | default('') }}/defaults"
          - "{{ template_dir }}/{{ vendor }}/{{ ansible_network_os }}/{{ platform | default('') }}/defaults"
          - "{{ template_dir }}/{{ vendor }}/{{ ansible_network_os }}/defaults"
          - "{{ template_dir }}/{{ vendor }}/defaults"
          - "./"
    ignore_errors: true
    register: "template_status"
    delegate_to: "localhost"

  - name: "{{ mock_dir | upper }}-> COMPARE EXPECTED TO TEST RESULTS"
    ntc_differ:
      pre_change: "{{ mock_path }}/{{ mock_dir }}/{{ inventory_hostname }}.cfg"
      post_change: "{{ test_path }}/{{ mock_dir }}/{{ inventory_hostname }}.cfg"
      dest: "./{{ test_path }}/test_results.cfg"
    register: "diff"
    when: "template_status['changed']"
    delegate_to: "localhost"

  - name: "{{ mock_dir | upper }}-> TEMPLATE FAILURE TO TEST RESULTS"
    copy:
      content: "{{ template_status['msg'] }}"
      dest: "./{{ test_path }}/test_results.cfg"
    when: "template_status is failed"
    delegate_to: "localhost"

  - name: "{{ mock_dir | upper }}-> SHOW THE DIFF"
    debug:
      var: "diff.diff_output"
    delegate_to: "localhost"

  - name: "{{ mock_dir | upper }}-> ASSERT THAT THERE IS NO DIFF"
    assert:
      that: 
        - "diff.diff_output == ''"
    ignore_errors: true
    register: "assert_result"
    delegate_to: "localhost"

  - debug: var=ansible_play_hosts
    delegate_to: localhost

  - name: "{{ mock_dir | upper }}-> GENERATE TEST LOG"
    template:
      src: "report.j2"
      dest: "{{ output_dir }}/reports/{{ mock_dir }}.txt" #_{{ inventory_hostname }}.txt"
    delegate_to: "localhost"
    run_once: true
